libconfuse/libconfuse

- .travis.yml
- README.md
- autogen.sh
This patch set adds support for Travis-CI, automatic builds at checkin,
and Coverity Scan for static code analysis.  It also contains a refactor
of the autogen.sh script to rely on autoreconf instead of calling each
autotool manually.
> Add support for Travis-CI and Coverity Scan

- src/confuse.c
- src/confuse.h
- tests/Makefile.am
- tests/section_remove.c
Hi!
I needed to remove sections, so that run-time changes could be seen when printing the config. Is this interesting at all?
Maybe I should free(opt->values) at the end of cfg_opt_rmnsec() if opt->nvalues drops to zero?
Cheers,
Peter
> Add functions to remove sections.

- windows/mingw/Makefile
I probably could've used ./configure to prevent this, but...
The lexer expects lex variables to be prefixed with cfg_yy, otherwise a number of undefined references will occur when compiling lexer.c. Add LFLAGS variable to ensure GNU Make runs lex with the extra required options.
> Update Makefile to fix lexer variable prefixes.

- src/confuse.c
- src/confuse.h
This also unifies the value argument so that it is never "taken over"
from the callee, which it was previously for titles of sections.
> Constify cfg_setopt

- src/confuse.c
I wrote a test for the section removal code in that other pull request and ran the testsuite for the first time and noticed that cfg_opt_getval asserts on multi-sections...
I came up with this fix.
Cheers,
Peter
> Allow cfg_opt_getval on options that are CFGF_MULTI sections.

- src/confuse.c
Especially do not free val->string and leave the pointer on ->parsecb
failure, causing a double free later.
> In cfg_setopt, do not lose the old value if the new value fails to parse.

- configure.ac
These checks are slow and no longer needed since we simplified the tests.
> configure.ac: Get rid of unneeded tests for internet-related functions

- windows/appveyor/msys2-build.ps1
I am thinking it would be nice to set up AppVeyor to automatically build and test the library with MSYS2 in Windows whenever the martinh master branch is updated.  We have to tell AppVeyor what commands to run, and those commands can either be in the form of an MsBuild project, a PowerShell script, or a Batch script.  This pull request adds an appropriate PowerShell script.
This PowerShell script doesn't necessarily have to be in the repository; you could choose to just copy and paste it into the web interface of AppVeyor instead.  However, putting it in the repository allows us to keep track of its version history and makes it easier for others to use it.
AppVeyor actually has MSYS2 installed by default, so we don't need to do any work to install MSYS2.
Here is an example of the build …
> PowerShell script for AppVeyor/MSYS2

- CONTRIBUTING.md
- README.md
- examples/cfgtest.c
- examples/cli.c
- examples/ftpconf.c
- examples/reread.c
- examples/simple.c
- indent.sh
- src/confuse.c
- src/confuse.h
- tests/env.c
- tests/ignore_parm.c
- tests/include.c
- tests/list_plus_syntax.c
- tests/quote_before_print.c
- tests/searchpath.c
- tests/section_remove.c
- tests/section_title_dupes.c
- tests/single_title_sections.c
- tests/suite_dup.c
- tests/suite_func.c
- tests/suite_list.c
- tests/suite_single.c
- tests/suite_validate.c
This pull request reindents the code base to Linux coding style, as proposed in issue #33,
skipping only the Windows specific code in `windows/` and `examples/wincfgtest.c`.
> Fix issue #33: Reindent to Linux coding style

- examples/.gitignore
- src/confuse.c
- src/confuse.h
- src/lexer.l
- tests/.gitignore
This pull request is a mix of `.gitignore` updates, doc comment fixes from
previous pull request, whitespace and readability cleanup.  But the most
important patch is the last one which replaces the use of `assert()` as a
means of verifying OS memory allocation with NULL returns.
> Do not use assert() for checking OS API functions

- src/confuse.c
Reported by Thomas Adam.
Signed-off-by: Peter Rosin <peda@lysator.liu.se>
> Abort on init with duplicate options (i.e. options with the same name).

- .travis.yml
Installing autopoint using the old "sudo" method has been deprecated and now removed by Travis-CI. The new dockerized non-sudo builds work fine since autopoint is on their whitelist.
> Fix Travis-CI problems by migrating to dockerized build

- ChangeLog.md
- examples/ftpconf.c
- examples/reread.c
- examples/simple.c
- src/confuse.c
- src/confuse.h
As reported by Peter Rosin in GitHub issue #46, calling `setlocale()` unconditionally from within the library may interfere with and override what the application using libConfuse actually wants.
This patch removes the calls to `setlocale()`, while at the same time fixing a possible ordering issue with the call to `bindtextdomain()`, and also updates the documentation, including the examples referenced by the API documentation.
> Fix issue #46: cfg_init() unconditionally calls setlocale()

- examples/Makefile.am
- examples/deprecated.c
- examples/deprecated.conf
- src/confuse.c
- src/confuse.h
Fix issue #24 
- `CFGF_DEPRECATED` causes a deprecated warning message for an option
- `CFGF_DEPRECATED | CFGF_DROP` causes a deprecated option to be dropped
Note: `CFGF_DROP` must currently be used with `CFG_DEPRECATED` to have
an effect on the option.
Signed-off-by: Sebastian Geiger <sbastig@gmx.net>
> Add support for CFGF_DEPRECATED and CFGF_DROP option flags

- src/lexer.l
> Include unistd.h on UNIX systems, for isatty()

- autogen.sh
- configure.ac
While running autoreconf it warns for a deprecated construct that
comes from our hard coded version of gettext:
configure.ac:27: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:27: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:27: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
This patch bumps the gettext version to 0.18.3, which is included
in the latest Ubuntu and Debian stable releases.
> Fix warning for deprecated AM_PROG_MKDIR_P macro in AM_GNU_GETTEXT

- src/confuse.c
struct stat st and int err in function cfg_searchpath() aren't usable
if HAVE_SYS_STAT_H isn't defined and they break the build with MSVC.
And conditionals with omitted operands are a GNU extension and not
supported by MSVC.
> Fixed MSVC build errors

- examples/.gitignore
- examples/Makefile.am
- examples/addsec.c
- src/confuse.c
- src/confuse.h
- tests/Makefile.am
- tests/section_add.c
> Add function to create a new titled section

- configure.ac
Unfortunately CentOS7, RHEL7 ships 0.18.2.1, so for best compat.
level at this point in time we set 0.18.2.
> Fix configure problem with gettext on CentOS/RHEL7

- CONTRIBUTING.md
- doc/tutorial.xml
Just fixing typos in the docs.
Signed-off-by: Luca Ceresoli <luca@lucaceresoli.net>
> Fix typos in documentation

- configure.ac
- src/Makefile.am
- src/confuse.c
- src/lexer.l
- tests/.gitignore
- tests/Makefile.am
- tests/section_title_dupes.c
This patch series unifies the API between the lexer and the `confuse.c` parser, simplifies the code, and fixes a few memory leaks due to unclosed file descriptors, lost `strdup()`'s, and, most importantly, adds a call to `cfg_yylex_destroy()` in `cfg_free()` as proposed in #21.
Seeing as this is quite a big pull request I will let it sit for a while to allow for a proper review.
> Fix #21: Refactor of lexer and fix memory leaks

- configure.ac
- src/Makefile.am
- src/confuse.c
- src/fmemopen.c
Tested on MacOS X El Capitan 10.11.6
> Fix #79: Add fmemopen() support using BSD funopen()

- src/confuse.h
Fix -> warning: missing initializer for member ‘cfg_opt_t::freecb’
> Fix -> warning: missing initializer for member ‘cfg_opt_t::freecb’

- src/confuse.c
- src/confuse.h
- tests/annotate.c
- Fix search path for annotate.conf when using separate build directory
- Conditionalize option annotation, user must set CFGF_COMMENTS to enable feature
> Annotate fixes

- src/confuse.h
On Windows, `DLLIMPORT` is expanded as `__declspec (dllexport)` or `__declspec (dllimport)` . All these two forms is not suitable for building `libconfuse` as a static library.
And since`confuse.c` includes `config.h` first, just before including `confuse.h`:
```c
#ifdef HAVE_CONFIG_H
#endif
...
#include "confuse.h"
```
so it is not possible to redefine `DLLIMPORT` in `config.h`.
This patch provides static library building support for Windows by adding a `BUILDING_STATIC` macro.
> Add static lib building support for Windows

- CONTRIBUTING.md
- indent.sh
Linux coding style link in https://github.com/martinh/libconfuse/blob/master/CONTRIBUTING.md has been moved to another page: https://www.kernel.org/doc/Documentation/process/coding-style.rst
There is also a HTML version of this page: https://www.kernel.org/doc/html/latest/process/coding-style.html
This PR updates the coding style link in `CONTRIBUTING.md` to the HTML version and updates the link in `indent.sh` to the non-HTML version.
> Fix Linux coding style link

- src/fmemopen.c
On Windows, we can not use 'CreateFile' within an UWP application:
> warning C4013: 'CreateFile' undefined; assuming extern returning int
(UWP applications can use CreateFile2 though. An example: https://github.com/microsoft/vcpkg/blob/master/ports/libsndfile/uwp-createfile-getfilesize.patch)
This patch uses `_open` as a replacement of `CreateFile`:
https://github.com/DanBloomberg/leptonica/blob/4972d55fcddee5c51f393747848c87fa54a64a78/src/utils2.c#L1926-L1973
Test with UWP under this PR: https://github.com/microsoft/vcpkg/pull/7252
> fmemopen.c: Add UWP support

- src/confuse.c
- tests/Makefile.am
- tests/suite_ptr.c
I noticed that comments where not strdup-ed, which would lead to use -after-free and eventually a double-free, if/when both the copy and the original try to free the same comment. I think this is perhaps not normally a problem because comments are not used heavily?
The second patch similarly prevents use-after-free and double-free if the dupopt operation fails in the middle. Failure should be rare though.
> cfg_dupopt_array fixes

- src/confuse.c
- tests/Makefile.am
- tests/empty_string.c
This fixes the round-trip case where an empty string is given in a cfg file, and a new cfg file is generated (possibly with unrelated changes to other options) with the intention of later using it as input.
Without these changes the above is broken when the string option has a default value.
> Print empty strings without commenting them out

- src/confuse.c
- tests/Makefile.am
- tests/setopt_ptr.c
Sometimes, cfg_setopt fails to free the old ptr value. If CFGF_RESET is set, the free happens, but all other cfg_setopt for ptr options leak unless the caller takes care of it. But cfg_setopt is an exported interface. Fix it the the same way cfg_setopt frees strings when CFGF_RESET is not set.
> cfg_setopt leaks ptr option values

- src/confuse.c
- tests/Makefile.am
- tests/setmulti_reset.c
It is desirable to fail gracefully and leave the configuration unaffected by imperfect input. Remember that cfg_setmulti is the heart of the cli example and needs to fail as gracefully as possible since it is used to parse end user input.
> Avoid clobbering CFGF_RESET when cfg_setmulti fails

- examples/cli.c
- src/confuse.c
- src/confuse.h
- tests/Makefile.am
- tests/modified_flag.c
- tests/print_filter.c
My use case is a somewhat big config file where not all options are applicable in all cases. The program is also able to modify options at run-time, and I would like to be able to sanely implement a save-config function that does not expose a lot of unrelated config options for that particular instance.
I came up with these changes. There are naturally more than one way to solve "my" use case, but I think this is a good way since the API is left pretty much untouched which is a good thing for all others that are not necessarily interested in filtering or options that may or may not be modified.
> Add modified flag, and selective printing

- examples/cli.c
- src/confuse.c
- tests/Makefile.am
- tests/section_getopt.c
- tests/section_remove.c
Hi!
This is more of a request for comments than a "normal" pull-request. That said, I would not be sorry if it was accepted as-is... The "status" is RFC, because this introduces a minor (if you ask me) incompatible change, as can be seen by the tweaks needed in the test suite. That incompatibility could perhaps be handled with some alternate notation? I didn't want to come up with something on my own, since I do not have a clear picture of the exact naming rules and what a non-invasive and non-ambiguous notation would be.
What I mean by alternate notation, is that perhaps instead of "sub|title|option", it could be "sub+title|option" or something along those lines, but + can clearly be a part of any option name, so it is not quite as simple as that...
The cli patch is really unrelated, and …
> RFC: cfg_getopt multi sub-section awareness

- .travis.yml
> Travis-CI: Drop sudo and Trusty requirement, Xenial new default

- configure.ac
- examples/.gitignore
- examples/Makefile.am
- examples/env.c
- examples/env.conf
- src/Makefile.am
- src/confuse.c
- src/confuse.h
- src/reallocarray.c
- tests/.gitignore
- tests/Makefile.am
- tests/keyval.c
This pull request adds a completely new section flag CFGF_KEYVAL, which can be used to read free-form key=value string options from files/buffers and access them as any other pre-runtime known option.
> Free-form dynamic key=value sections

- examples/cfgtest.c
- examples/cli.c
- examples/ftpconf.c
- examples/reread.c
- src/confuse.c
- src/confuse.h
- src/lexer.l
When working on [genimage](https://github.com/pengutronix/genimage) and trying to make it sparse clean I noticed that most warnings there originate from libconfuse. This pull request addresses the warnings
warning: Using plain integer as NULL pointer
. The first two fix these in the public header, the third commit fixes the source code of libconfuse itself.
> Use NULL to initialize pointers

- configure.ac
fixes
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.20
support compiling if gettext 0.20 or later is found
AM_GNU_GETTEXT_REQUIRE_VERSION overwrites AM_GNU_GETTEXT_VERSION if autoreconf supports it, so legacy systems are still supported
> configure.ac: enable successful compile with gettext 0.20

- src/confuse.c
Do not print an error about 'no such option <x>' when the section has flag CFGF_KEYSTRVAL set.
Fixes #160
> Remove 'no such option' errors for KEYSTRVAL sections

- configure.ac
Automatically enable large filesystem support so we use the newer interfaces when interacting with the filesystem.  Without this, code that tries to stat a file with 64-bit inodes can fail if the stat structure is only 32-bit (which is common on x86 & arm).  On Linux, this can manifest with some filesystems more often than others.
Practically speaking, since libconfuse doesn't do too much file I/O, the overhead should be non-existent.  Especially since the C library (e.g. glibc) is already using the 64-bit syscall even if the function call was 32-bit.
On systems that have 64-bit stat already (which is common on x86_64 and aarch64), there is no overhead as the code is exactly the same.
> configure.ac: enable automatic LFS support

- src/confuse.h
Format attributes help compilers to warn on format string misuses, like:
cfg_error(cfg, user_defined_input)  // potential security issue
cfg_error(cfg, "foo %d", "bar")
confuse.c:1246:20: warning: format string is not a string literal [-Wformat-nonliteral]
vfprintf(stderr, fmt, ap);
^~~
Guard the annotation with `__GNUC__`, defined by GCC and Clang, which support the GNU extension of function format attributes.
TODO: Untested on Windows.
> Annotate cfg_error with format attribute
