libconfuse/libconfuse

- src/confuse.c
While manually testing libConfuse I found that it complained about
unknown options even though CFGF_IGNORE_UNKNOWN was set.
This patch complements commit 0255c50 with an extra check for the
CFGF_IGNORE_UNKNOWN flag in cfg_getopt().
> Silence 'no such option' when CFGF_IGNORE_UNKNOWN is set.

- examples/Makefile.am
- examples/nested.c
- examples/nested.conf
> Fix issue #42: Add nested.conf example from Thomas Adam

- doc/Doxyfile.in
- doc/doxygen-footer.html
- doc/doxygen-header.html
- doc/doxygen.css
> Update generated API docs to modern Doxygen

- .travis.yml
> Update Travis-CI build script for Coverity runs

- examples/cli.c
- examples/reread.c
- src/confuse.c
Fixes to bugs and regressions since last stable release.
> Coverity fixes

- CONTRIBUTING.md
> Fix #56: Update CONTRIBUTING document with a section on writing tests

- ChangeLog.md
- configure.ac
> Update ChangeLog and bump version to v2.9-rc1 for testing phase

- .travis.yml
> Due to new requirements on GNU gettext we need at least Ubuntu 14.04

- HACKING.md
> Clarify maintenance and release checklists, update ABI versioning

- src/lexer.l
- tests/include.c
Test case and bugfix are provided.
> SIGSEGV when parsed default values are used with include

- libconfuse.spec.in
> Fix #71: Change Copyright --> License in .rpm specfile

- ChangeLog.md
- configure.ac
> Update ChangeLog and bump version to v3.1-beta1

- HACKING.md
> Minor whitespace fix

- src/confuse.h
> Document new cfg_validate_callback2_t support

- src/confuse.h
> Add missing init of CFG_STR_LIST() for new validation cb

- ChangeLog.md
- HACKING.md
- README.md
- configure.ac
- m4/Makefile.am
- po/de.po
- po/fr.po
- po/sv.po
- src/Makefile.am
- tests/Makefile.am
- Add a few ABI version examples to `HACKING.md`
- Update ABI version
- Update ChangeLog
- Bump version to v3.1
> Prepare v3.1 release

- .gitignore
- configure.ac
- examples/.gitignore
- examples/Makefile.am
- examples/addsec.c
- examples/ftpconf.c
- examples/parsebuf.c
- examples/reread.c
- examples/simple.c
- src/fmemopen.c
> Windows mingw fixes

- ChangeLog.md
- configure.ac
- src/Makefile.am
> Fix #101: Bump ABI 1.1.0 --> 2.0.0 and prepare release v3.2.1

- src/confuse.c
CFG_INT now supports taking binary prefix `0b` to allow binary literals to be parsed too.
> Support binary radix for CFG_INT

- src/confuse.c
> only apply search path logic to relative pathnames
